
name: TaskMaster API CI
on:
  push:
    branches: [ci/cid-practice, main]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Use version 18 of Node.JS
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: npm install
